version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/back"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/pdf"
    schedule:
      interval: "daily"
    target-branch: "dev"
