version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/back"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/search"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/doc"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
