version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/back"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/doc"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "production"
