export const SSD_HEADERS = {
  reason: "Motif",
  publicId: "Numéro unique",
  reportAsSiret: "SIRET du déclarant",
  reportForSiret: "SIRET de l'émetteur",
  useDate: "Date d'utilisation",
  dispatchDate: "Date d'expédition",
  wasteCode: "Code déchet",
  wasteDescription: "Dénomination du déchet",
  wasteCodeBale: "Code déchet Bâle",
  secondaryWasteCodes: "Codes déchets secondaires",
  secondaryWasteDescriptions: "Dénominations des déchets secondaires",
  product: "Produit",
  weightValue: "Poids en tonne",
  weightIsEstimate: "Type de poids",
  volume: "Volume en M3",
  processingDate: "Date de traitement",
  processingEndDate: "Date de fin de traitement",
  destinationType: "Type de destinataire",
  destinationOrgId: "Numéro d'identification du destinataire",
  destinationName: "Raison sociale du destinataire",
  destinationAddress: "Adresse du destinataire",
  destinationCity: "Commune du destinataire",
  destinationPostalCode: "Code postal du destinataire",
  destinationCountryCode: "Code pays du destinataire",
  operationCode: "Code d'opération",
  operationMode: "Mode de traitement",
  administrativeActReference: "Référence de l'acte administratif"
};
