version: "3.7"
services:
  td-api:
    restart: "no"
    build:
      context: ./back
      dockerfile: Dockerfile.test
    environment:
      JWT_SECRET: "xxx"
      EMAIL_BACKEND: "sendinblue"
      MOCK_SIB_URL: "true"
      MAIN_TEMPLATE_ID: "9"
      ONBOARDING_TEMPLATE_ID: "8"
      SECOND_ONBOARDING_TEMPLATE_ID: "7"
      SECURITY_CODE_RENEWAL_TEMPLATE_ID: "6"


  td-ui:
    restart: "no"
    build:
      context: ./front
      dockerfile: Dockerfile.test
    environment:
      - CI=true
