version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.33.0
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            migrations: true

  postgres:
    image: postgres:10.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data

  td-api:
    image: td-api
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: dev
      VIRTUAL_HOST: $API_HOST
      LETSENCRYPT_HOST: $API_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT

  td-ui:
    image: td-ui
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    environment:
      VIRTUAL_HOST: $UI_HOST
      LETSENCRYPT_HOST: $UI_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT

  td-insee:
    image: td-insee
    build:
      context: ./insee
      dockerfile: Dockerfile
    restart: always
    environment:
      INSEE_SECRET: $INSEE_SECRET

  td-pdf:
    image: td-pdf
    build:
      context: ./pdf
      dockerfile: Dockerfile
    restart: always

  td-mail:
    image: td-mail
    build:
      context: ./mail
      dockerfile: Dockerfile
    restart: always
    environment:
      MJ_APIKEY_PUBLIC: $MJ_APIKEY_PUBLIC
      MJ_APIKEY_PRIVATE: $MJ_APIKEY_PRIVATE

  td-doc:
    image: td-doc
    build:
      context: ./documentation
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: $DOC_HOST
      LETSENCRYPT_HOST: $DOC_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT

volumes:
  postgres:

networks:
  default:
    external:
      name: nginx-proxy
