version: "3"
services:
  postgres:
    image: betagouv/trackdechets-postgres:sandbox

  td-api:
    image: betagouv/trackdechets-api:sandbox

  td-ui:
    image: betagouv/trackdechets-ui:sandbox

  td-insee:
    image: betagouv/trackdechets-insee:sandbox

  td-pdf:
    image: betagouv/trackdechets-pdf:sandbox

  td-mail:
    image: betagouv/trackdechets-mail:sandbox

  td-doc:
    image: betagouv/trackdechets-doc:sandbox

  td-etl:
    image: betagouv/trackdechets-etl:sandbox

