version: "3"
services:

  postgres:
    image: betagouv/trackdechets-postgres:dev
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      AIRFLOW_POSTGRES_USER: $AIRFLOW_POSTGRES_USER
      AIRFLOW_POSTGRES_PASSWORD: $AIRFLOW_POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data

  td-api:
    image: betagouv/trackdechets-api:dev
    environment:
      NODE_ENV: dev

  td-ui:
    image: betagouv/trackdechets-ui:dev

  td-pdf:
    image: betagouv/trackdechets-pdf:dev
    environment:
      PDF_WATERMARK: display

  td-mail:
    image: betagouv/trackdechets-mail:dev

  td-doc:
    image: betagouv/trackdechets-doc:dev

  # Simple Nginx container to redirect doc.trackdechets.fr
  # to developers.trackdechets.fr/docs
  td-doc-redirect:
    image: betagouv/trackdechets-doc-redirect:dev
    environment:
      VIRTUAL_HOST: $DOC_HOST
      LETSENCRYPT_HOST: $DOC_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT
      DEVELOPERS_HOST: $DEVELOPERS_HOST
      DEVELOPERS_URL_SCHEME: $DEVELOPERS_URL_SCHEME

  td-etl:
    image: betagouv/trackdechets-etl:dev

