version: "3"
services:
  postgres:
    image: betagouv/trackdechets-postgres:dev

  td-api:
    image: betagouv/trackdechets-api:dev
    environment:
      NODE_ENV: dev

  td-ui:
    image: betagouv/trackdechets-ui:dev

  td-insee:
    image: betagouv/trackdechets-insee:dev

  td-pdf:
    image: betagouv/trackdechets-pdf:dev
    environment:
      PDF_WATERMARK: display

  td-mail:
    image: betagouv/trackdechets-mail:dev

  td-doc:
    image: betagouv/trackdechets-doc:dev

  td-etl:
    image: betagouv/trackdechets-etl:dev

