version: "3.7"
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    restart: always
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "6379:6379"

  td-api:
    image: td-api
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./back/src:/usr/src/app/src
      - ./doc/docs:/usr/src/doc/docs
      - ./front/src/generated:/usr/src/front/src/generated
      - ./back/prisma:/usr/src/app/prisma
    env_file:
      - .env
    environment:
      NODE_ENV: dev
      SIB_BASE_URL: "http://mailservice"
    ports:
      - "4000:80"

  td-ui:
    stdin_open: true
    image: node:10.14-alpine
    container_name: td-ui
    working_dir: /usr/src/front
    command: sh -c "npm install && npm start"
    expose:
      - "3000"
    volumes:
      - ./front/:/usr/src/front
    ports:
      - "3000:3000"

  td-doc:
    image: td-doc
    build:
      context: ./doc
      dockerfile: Dockerfile.dev
    volumes:
      - ./doc/docs:/app/docs
      - ./doc/website/core:/app/website/core
      - ./doc/website/pages:/app/website/pages
      - ./doc/website/static:/app/website/static
      - ./doc/website/sidebars.json:/app/website/sidebars.json
      - ./doc/website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website
    ports:
      - "5000:3000"

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      API_HOST: $API_HOST
      API_PORT: $API_PORT
      UI_HOST: $UI_HOST
      DEVELOPERS_HOST: $DEVELOPERS_HOST
    ports:
      - "80:80"

volumes:
  postgres: