version: "3.7"
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    restart: always
    sysctls:
      - net.core.somaxconn=511

  td-api:
    image: td-api
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./back/src:/usr/src/app/src
      - ./back/prisma:/usr/src/app/prisma
      - ./doc/docs:/usr/src/app/documentation
      - ./front/src/generated:/usr/src/app/front/generated
    env_file:
      - .env
    environment:
      NODE_ENV: dev
      DATABASE_URL: $DATABASE_URL
      VIRTUAL_HOST: $API_HOST
      LETSENCRYPT_HOST: $API_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT

  td-ui:
    stdin_open: true
    image: node:10.14-alpine
    container_name: td-ui
    working_dir: /usr/src/front
    command: sh -c "npm install && npm start"
    expose:
      - "3000"
    environment:
      VIRTUAL_HOST: $UI_HOST
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: $UI_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT
    volumes:
      - ./front/:/usr/src/front

  td-doc:
    image: td-doc
    build:
      context: ./doc
      dockerfile: Dockerfile.dev
    volumes:
      - ./doc/docs:/app/docs
      - ./doc/website/core:/app/website/core
      - ./doc/website/pages:/app/website/pages
      - ./doc/website/static:/app/website/static
      - ./doc/website/sidebars.json:/app/website/sidebars.json
      - ./doc/website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website
    environment:
      VIRTUAL_HOST: $DEVELOPERS_HOST
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: $DEVELOPERS_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT

volumes:
  postgres:

networks:
  default:
    external:
      name: nginx-proxy
