version: "3"
services:
  reverse-proxy:
    image: traefik:1.7.4
    command: --docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            migrations: true

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data

  td-api:
    image: td-api
    build:
      context: ./back
      dockerfile: Dockerfile
    command: npx nodemon -L --watch src --exec npm start
    volumes:
      - ./back/src:/usr/src/app/src
    environment:
      NODE_ENV: dev
    labels:
      - "traefik.frontend.rule=Host:$API_HOST"

  td-ui:
    image: td-ui
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_ENDPOINT: $API_HOST
    labels:
      - "traefik.frontend.rule=Host:$UI_HOST"

  td-insee:
    image: td-insee
    build:
      context: ./insee-go
      dockerfile: Dockerfile
    ports:
      - "81:81"
    environment:
        INSEE_SECRET: $INSEE_SECRET

volumes:
  postgres:
