version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.33.0
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            migrations: true

  postgres:
    image: td-postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    restart: always
    sysctls:
      - net.core.somaxconn=511

  td-api:
    image: td-api
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: dev
      JWT_SECRET: $JWT_SECRET
      UI_HOST: $UI_HOST
      VIRTUAL_HOST: $API_HOST
      LETSENCRYPT_HOST: $API_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT
      TRELLO_API_KEY: $TRELLO_API_KEY
      TRELLO_TOKEN: $TRELLO_TOKEN
      TRELLO_ALERTS_LIST_ID: $TRELLO_ALERTS_LIST_ID
      SENTRY_DSN: $SENTRY_DSN
      MJ_MAIN_TEMPLATE_ID: $MJ_MAIN_TEMPLATE_ID
      MJ_FIRST_ONBOARDING_TEMPLATE_ID: $MJ_FIRST_ONBOARDING_TEMPLATE_ID
      MJ_SECOND_ONBOARDING_TEMPLATE_ID: $MJ_SECOND_ONBOARDING_TEMPLATE_ID
      NOTIFY_DREAL_WHEN_FORM_DECLINED: $NOTIFY_DREAL_WHEN_FORM_DECLINED

  td-ui:
    image: td-ui
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        build_env: recette
    restart: always
    environment:
      VIRTUAL_HOST: $UI_HOST
      LETSENCRYPT_HOST: $UI_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT

  td-insee:
    image: td-insee
    build:
      context: ./insee
      dockerfile: Dockerfile
    restart: always
    environment:
      INSEE_SECRET: $INSEE_SECRET
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  td-pdf:
    image: td-pdf
    build:
      context: ./pdf
      dockerfile: Dockerfile
    restart: always
    environment:
      SENTRY_DSN: $SENTRY_DSN

  td-mail:
    image: td-mail
    build:
      context: ./mail
      dockerfile: Dockerfile
    restart: always
    environment:
      MJ_APIKEY_PUBLIC: $MJ_APIKEY_PUBLIC
      MJ_APIKEY_PRIVATE: $MJ_APIKEY_PRIVATE

  td-doc:
    image: td-doc
    build:
      context: ./documentation
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: $DOC_HOST
      LETSENCRYPT_HOST: $DOC_HOST
      LETSENCRYPT_EMAIL: $EMAIL_LETS_ENCRYPT

  td-etl:
    image: td-etl
    build:
      context: ./etl
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    environment:
      POSTGRES_USER: $AIRFLOW_POSTGRES_USER
      POSTGRES_PASSWORD: $AIRFLOW_POSTGRES_PASSWORD
      AIRFLOW__CORE__FERNET_KEY: $AIRFLOW_FERNET_KEY
      AIRFLOW__CORE__LOGGING_LEVEL: ERROR
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://$AIRFLOW_POSTGRES_USER:$AIRFLOW_POSTGRES_PASSWORD@postgres:5432/airflow
      AIRFLOW_CONN_POSTGRES_ETL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$ETL_DB
      AIRFLOW_CONN_POSTGRES_PRISMA: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/prisma

  metabase:
    image: metabase/metabase
    volumes:
      - metabase:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - VIRTUAL_HOST=$METABASE_HOST
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=$METABASE_HOST
      - LETSENCRYPT_EMAIL=$EMAIL_LETS_ENCRYPT

volumes:
  postgres:
  metabase:

networks:
  default:
    external:
      name: nginx-proxy
