export const GET_BSDS_ACTOR_MAX_LENGTH = 50;
export const GET_BSDS_READABLE_ID_MAX_LENGTH = 30;
export const GET_BSDS_PLATES_MAX_LENGTH = 20;
export const GET_BSDS_CUSTOM_INFO_MAX_LENGTH = 20;
export const GET_BSDS_WASTE_MAX_LENGTH = 30;
