version: "3"
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: no_pass

  redis:
    image: redis:5.0-alpine
    restart: always
    sysctls:
      - net.core.somaxconn=511

  td-api:
    image: td-api
    build:
      context: ../
      dockerfile: Dockerfile.dev
    command: npx nodemon -L --watch src --exec "ts-node" --project ../tsconfig.json -r tsconfig-paths/register src/index.ts
    volumes:
      - ../src:/usr/src/app/src
    env_file:
      - .integration-tests-env
    environment:
      NODE_ENV: test
      VIRTUAL_HOST: $API_HOST
      LETSENCRYPT_HOST: $API_HOST
      EMAIL_BACKEND: "sendinblue"
      MAIN_TEMPLATE_ID: "9"

