version: "3"
services:
  # postgres:
  #   image: postgres:13.3-alpine
  #   restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  #   environment:
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: no_pass

  # redis:
  #   image: redis:5.0-alpine
  #   restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  #   sysctls:
  #     - net.core.somaxconn=511

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  #   restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   deploy:
  #     placement:
  #       constraints:
  #         - "node.labels.elasticsearch == true"

  # mongodb:
  #   image: mongo:6
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=test
  #     - MONGO_INITDB_ROOT_PASSWORD=no_pass

  td-api:
    image: td-api
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ../
      dockerfile: Dockerfile.dev
    command: [ "npm", "run", "dev:integration" ]
    volumes:
      - ../src:/usr/src/app/src
    env_file:
      - .integration-tests-env
    environment:
      NODE_ENV: test
      VIRTUAL_HOST: $API_HOST
      LETSENCRYPT_HOST: $API_HOST
      EMAIL_BACKEND: "sendinblue"
      SIB_BASE_URL: "http://mailservice"
      MAIN_TEMPLATE_ID: "9"
      FIRST_ONBOARDING_TEMPLATE_ID: "246"
      PRODUCER_SECOND_ONBOARDING_TEMPLATE_ID: "248"
      PROFESIONAL_SECOND_ONBOARDING_TEMPLATE_ID: "250"
      VERIFIED_FOREIGN_TRANSPORTER_COMPANY_TEMPLATE_ID: "247"
      SENDER_EMAIL_ADDRESS: "us@td.test"
      SENDER_NAME: "Wastetracker corp."
      POST_BACKEND: console
      ELASTIC_SEARCH_URL: $ELASTIC_SEARCH_URL
      QUEUE_NAME_SENDMAIL: td-integration-tests-queue
      REGISTRY_WHITE_LIST_IP: "11.11.11.11"
