version: "3"
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: no_pass

  redis:
    image: redis:5.0-alpine
    restart: always
    sysctls:
      - net.core.somaxconn=511

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - "node.labels.elasticsearch == true"

  td-api:
    image: node:14.15.4
    command: sh -c "yarn && yarn generate && yarn dev"
    working_dir: /usr/src/back
    volumes:
      - ./back:/usr/src/back
      - ./package.json:/usr/src/package.json
      - ./yarn.lock:/usr/src/yarn.lock
      - ./.yarn:/usr/src/.yarn
      - ./.yarnrc.yml:/usr/src/.yarnrc.yml
      - ./common:/usr/src/common
      - ./search:/usr/src/search
    env_file:
      - .integration-tests-env
    environment:
      NODE_ENV: test
      VIRTUAL_HOST: $API_HOST
      LETSENCRYPT_HOST: $API_HOST
      EMAIL_BACKEND: "sendinblue"
      SIB_BASE_URL: "http://mailservice"
      MAIN_TEMPLATE_ID: "9"
      FIRST_ONBOARDING_TEMPLATE_ID: "12"
      PRODUCER_SECOND_ONBOARDING_TEMPLATE_ID: "10"
      PROFESSIONAL_SECOND_ONBOARDING_TEMPLATE_ID: "11"
      SENDER_EMAIL_ADDRESS: "us@td.test"
      SENDER_NAME: "Wastetracker corp."
      POST_BACKEND: console
      ELASTIC_SEARCH_URL: $ELASTIC_SEARCH_URL
      QUEUE_NAME_SENDMAIL: td-integration-tests-queue
