services:
  postgres:
    extends:
      file: ../../docker-compose.dbs.yml
      service: postgres

  redis:
    extends:
      file: ../../docker-compose.dbs.yml
      service: redis

  elasticsearch:
    extends:
      file: ../../docker-compose.dbs.yml
      service: elasticsearch

  mongodb:
    extends:
      file: ../../docker-compose.dbs.yml
      service: mongodb

  nginx:
    extends:
      file: ../../docker-compose.yml
      service: nginx

  td-api:
    image: td-api
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ../../
      dockerfile: ./back/integration-tests/Dockerfile
    volumes:
      - ../src:/usr/src/app/back/src
    env_file:
      - .integration-tests-env
    environment:
      NODE_ENV: test
      VIRTUAL_HOST: $API_HOST
      LETSENCRYPT_HOST: $API_HOST
      EMAIL_BACKEND: "sendinblue"
      SIB_BASE_URL: "http://mailservice"
      MAIN_TEMPLATE_ID: "9"
      FIRST_ONBOARDING_TEMPLATE_ID: "246"
      PRODUCER_SECOND_ONBOARDING_TEMPLATE_ID: "248"
      PROFESIONAL_SECOND_ONBOARDING_TEMPLATE_ID: "250"
      VERIFIED_FOREIGN_TRANSPORTER_COMPANY_TEMPLATE_ID: "247"
      SENDER_EMAIL_ADDRESS: "us@td.test"
      SENDER_NAME: "Wastetracker corp."
      POST_BACKEND: console
      QUEUE_NAME_SENDMAIL: td-integration-tests-queue
      REGISTRY_WHITE_LIST_IP: "11.11.11.11"
