# Use the specific version of the node image used in production
FROM node:18
# Set the working directory inside the container
WORKDIR /usr/src/app
# Only copy the package.json and package-lock.json (if it exists) to ensure that
# the npm install command is cached unless these files change.
COPY package*.json ./
# Install dependencies.
RUN npm install --quiet --no-audit
# After installing the dependencies, copy the rest of the application.
COPY . .
# The command to run on container start
CMD [ "npm", "run", "dev" ]
