version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/project/trackdechets

jobs:
  lint:
    description: "Run linter"
    executor: node
    steps:
      - checkout
      - run:
          name: "back: Install dependencies"
          command: npm ci --prefix back
      - run:
          name: "back: Run linter"
          command: npm run lint --prefix back
      - run:
          name: "front: Install dependencies"
          command: npm ci --prefix front
      - run:
          name: "front: Run linter"
          command: npm run lint --prefix front

  test:
    description: "Run tests"
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            for container in $(docker-compose -f docker-compose.test.yml ps --services | tr '\r\n' '\n');
            do
              docker-compose -f docker-compose.test.yml run --rm $container
              code=$?
              if [[ $code != "0" ]]; then
                echo "Tests failed for ${container}, exit code ${code}"
                exit 1
              fi
            done

  build-and-push:
    description: "Build all images, pushes them to the Docker repository if branch is master or dev"
    executor: node
    parameters:
      extra-cfg:
        type: string
        default: ""
      build-args:
        type: string
        default: ""
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build and push images"
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.build.yml << parameters.extra-cfg >> build << parameters.build-args >>
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "dev" ]; then
              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
              docker-compose -f docker-compose.yml -f docker-compose.build.yml << parameters.extra-cfg >> push --ignore-push-failures
            fi

  deploy:
    machine:
      enabled: true
    working_directory: ~/project/trackdechets
    parameters:
      user:
        type: env_var_name
        default: SSH_USER
      host:
        type: env_var_name
        default: SSH_HOST
      extra-cfg:
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Copy compose file
          command: |
            scp docker-compose.yml ${<< parameters.user >>}@${<< parameters.host >>}:/srv/trackdechets/
      - when:
          condition: << parameters.extra-cfg >>
          steps:
            - run:
                name: Copy extra compose config file
                command: |
                  scp << parameters.extra-cfg >> ${<< parameters.user >>}@${<< parameters.host >>}:/srv/trackdechets/docker-compose.override.yml
      - run:
          name: Deploy Over SSH
          command: |
            ssh ${<< parameters.user >>}@${<< parameters.host >>} "cd /srv/trackdechets/
                docker-compose pull
                if [ "${CIRCLE_BRANCH}" == "dev" ]; then
                  docker-compose up -d postgres td-doc-redirect
                fi
                docker-compose up -d prisma redis td-api td-ui td-mail td-doc
                docker exec \$(docker ps -qf 'name=td-api') npx prisma deploy"

  integration-tests:
    machine:
      enabled: true
    working_directory: ~/project/trackdechets
    steps:
      - checkout
      - run:
          name: Run integration tests
          command: |
            cd back/integration-tests
            sudo chmod +x ./run.sh
            ./run.sh

workflows:
  build-and-deploy:
    jobs:
      - lint
      - test
      - integration-tests
      - build-and-push:
          name: build-and-push-prod
          requires:
            - lint
            - test
            - integration-tests
          filters:
            branches:
              only: master
      - build-and-push:
          name: build-and-push-sandbox
          extra-cfg: "-f docker-compose.sandbox.yml"
          build-args: "--build-arg build_env=sandbox"
          requires:
            - lint
            - test
            - integration-tests
          filters:
            branches:
              only: master
      - build-and-push:
          name: build-and-push-recette
          extra-cfg: "-f docker-compose.val.yml"
          build-args: "--build-arg build_env=recette"
          requires:
            - lint
            - test
            - integration-tests
          filters:
            branches:
              only: dev
      - deploy:
          name: deploy-prod
          requires:
            - build-and-push-prod
          filters:
            branches:
              only: master
      - deploy:
          name: deploy-sandbox
          host: SSH_HOST_SANDBOX
          extra-cfg: "docker-compose.sandbox.yml"
          requires:
            - build-and-push-sandbox
          filters:
            branches:
              only: master
      - deploy:
          name: deploy-recette
          host: SSH_HOST_RECETTE
          extra-cfg: "docker-compose.val.yml"
          requires:
            - build-and-push-recette
          filters:
            branches:
              only: dev
