version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/project/trackdechets

jobs:
  check-docker:
    executor: node
    steps:
      - run: |
          if [[ -z "$DOCKERHUB_USER" || -z "$DOCKERHUB_PASSWORD" ]]; then
            echo "Missing DOCKERHUB_USER or DOCKERHUB_PASSWORD environment variables!"
            exit 1
          fi

  build-ui:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t betagouv/trackdechets-ui:$CIRCLE_SHA1 ./front
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
          docker push betagouv/trackdechets-ui:$CIRCLE_SHA1
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker tag betagouv/trackdechets-ui:$CIRCLE_SHA1 betagouv/trackdechets-ui:latest
            docker push betagouv/trackdechets-ui:latest
          fi

  build-api:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t betagouv/trackdechets-api:$CIRCLE_SHA1 ./back
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
          docker push betagouv/trackdechets-api:$CIRCLE_SHA1
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker tag betagouv/trackdechets-api:$CIRCLE_SHA1 betagouv/trackdechets-api:latest
            docker push betagouv/trackdechets-api:latest
          fi

  build-insee:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t betagouv/trackdechets-insee:$CIRCLE_SHA1 ./insee
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
          docker push betagouv/trackdechets-insee:$CIRCLE_SHA1
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker tag betagouv/trackdechets-insee:$CIRCLE_SHA1 betagouv/trackdechets-insee:latest
            docker push betagouv/trackdechets-insee:latest
          fi

  build-pdf:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t betagouv/trackdechets-pdf:$CIRCLE_SHA1 ./pdf
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
          docker push betagouv/trackdechets-pdf:$CIRCLE_SHA1
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker tag betagouv/trackdechets-pdf:$CIRCLE_SHA1 betagouv/trackdechets-pdf:latest
            docker push betagouv/trackdechets-pdf:latest
          fi

  build-mail:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t betagouv/trackdechets-mail:$CIRCLE_SHA1 ./mail
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
          docker push betagouv/trackdechets-mail:$CIRCLE_SHA1
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker tag betagouv/trackdechets-mail:$CIRCLE_SHA1 betagouv/trackdechets-mail:latest
            docker push betagouv/trackdechets-mail:latest
          fi

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker pull betagouv/trackdechets-api:latest"
            ssh $SSH_USER@$SSH_HOST "docker pull betagouv/trackdechets-ui:latest"
            ssh $SSH_USER@$SSH_HOST "cd /srv/trackdechets/ ; docker-compose up --force-recreate -d td-api td-ui"

workflows:
  build_deploy:
    jobs:
      - check-docker
      - build-ui:
          requires:
            - check-docker
      - build-api:
          requires:
            - check-docker
      - build-insee:
          requires:
            - check-docker
      - build-pdf:
          requires:
            - check-docker
      - build-mail:
          requires:
            - check-docker
      - deploy:
          requires:
            - build-api
            - build-ui
            - build-insee
            - build-pdf
            - build-mail
          filters:
            branches:
              only: master
