version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/project/trackdechets

jobs:
  build-docker-front:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          if [[ -z "$DOCKERHUB_USER" || -z "$DOCKERHUB_PASSWORD" ]]; then
            echo "Missing DOCKERHUB_USER or DOCKERHUB_PASSWORD environment variables!"
            exit 1
          fi
          docker build -t betagouv/trackdechets-ui:$CIRCLE_SHA1 --build-arg REACT_APP_API_ENDPOINT=api.trackdechets.beta.gouv.fr ./front
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
          docker push betagouv/trackdechets-ui:$CIRCLE_SHA1
          if [[ "$CIRCLE_BRANCH" = "master" ]]; then
            docker tag betagouv/trackdechets-ui:$CIRCLE_SHA1 betagouv/trackdechets-ui:latest
            docker push betagouv/trackdechets-ui:latest
          fi

  build-docker-back:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          if [[ -z "$DOCKERHUB_USER" || -z "$DOCKERHUB_PASSWORD" ]]; then
            echo "Missing DOCKERHUB_USER or DOCKERHUB_PASSWORD environment variables!"
            exit 1
          fi
          docker build -t betagouv/trackdechets-api:$CIRCLE_SHA1 ./back
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
          docker push betagouv/trackdechets-api:$CIRCLE_SHA1
          if [[ "$CIRCLE_BRANCH" = "master" ]]; then
            docker tag betagouv/trackdechets-api:$CIRCLE_SHA1 betagouv/trackdechets-api:latest
            docker push betagouv/trackdechets-api:latest
          fi

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker pull betagouv/trackdechets-api:latest"
            ssh $SSH_USER@$SSH_HOST "docker pull betagouv/trackdechets-ui:latest"
            ssh $SSH_USER@$SSH_HOST "cd /srv/trackdechets/ ; docker-compose up --force-recreate -d td-api td-ui"


workflows:
  build_deploy:
    jobs:
      - build-docker-front
      - build-docker-back
      - deploy:
          requires:
            - build-docker-front
            - build-docker-back
          filters:
            branches:
              only: master

