export const INCOMING_TEXS_HEADERS = {
  reason: "Motif",
  custominfo: "Champ libre / Référence chantier",
  publicId: "Numéro unique",
  reportAsSiret: "SIRET du déclarant",
  reportForSiret: "SIRET du destinataire",
  wasteCode: "Code déchet",
  wastePop: "POP",
  wasteIsDangerous: "Dangereux",
  receptionDate: "Date de réception",
  wasteDescription: "Dénomination du déchet",
  wasteCodeBale: "Code déchet Bâle",
  dap: "DAP",
  weightValue: "Poids en tonnes",
  weightIsEstimate: "Type de poids",
  volume: "Volume en M3",
  parcelInseeCodes: "Codes INSEE des parcelles",
  parcelNumbers: "Numéro(s) des parcelles",
  parcelCoordinates: "Coordonnées des parcelles",
  sisIdentifiers: "Identifiant SIS des terrains",
  producerType: "Type de producteur initial",
  producerOrgId: "Numéro d'identification du producteur initial",
  producerName: "Raison sociale du producteur initial",
  producerAddress: "Adresse du producteur initial",
  producerPostalCode: "Code postal du producteur initial",
  producerCity: "Commune du producteur initial",
  producerCountryCode: "Code pays du producteur initial",
  municipalitiesInseeCodes: "Code(s) INSEE de(s) commune(s)",
  municipalitiesNames: "Commune(s)",
  senderType: "Type d'expéditeur ou détenteur",
  senderOrgId: "Numéro d'identification de l'expéditeur ou détenteur",
  senderName: "Raison sociale de l'expéditeur ou détenteur",
  senderTakeOverAddress:
    "Libellé de l'adresse de prise en charge de l'expéditeur ou détenteur",
  senderTakeOverPostalCode:
    "Code postal de prise en charge de l'expéditeur ou détenteur",
  senderTakeOverCity: "Commune de prise en charge de l'expéditeur ou détenteur",
  senderTakeOverCountryCode:
    "Pays de prise en charge de l'expéditeur ou détenteur",
  senderAddress: "Adresse de l'expéditeur ou détenteur",
  senderPostalCode: "Code postal de l'expéditeur ou détenteur",
  senderCity: "Commune de l'expéditeur ou détenteur",
  senderCountryCode: "Pays de l'expéditeur ou détenteur",
  brokerSiret: "SIRET du courtier",
  brokerName: "Raison sociale du courtier",
  brokerReceiptNumber: "Numéro de récépissé du courtier",
  traderSiret: "SIRET du négociant",
  traderName: "Raison sociale du négociant",
  traderReceiptNumber: "Numéro de récépissé du négociant",
  operationCode: "Code d'opération réalisé",
  declarationNumber: "Numéro de déclaration",
  notificationNumber: "Numéro de notification",
  movementNumber: "Numéro de mouvement",
  nextOperationCode: "Code d'opération ultérieure prévue",
  isUpcycled: "Terre valorisée",
  destinationParcelInseeCodes:
    "Codes INSEE des parcelles de destination si valorisation",
  destinationParcelNumbers:
    "Numéro(s) des parcelles de destination si valorisation",
  destinationParcelCoordinates:
    "Coordonnées des parcelles de destination si valorisation",
  transporter1TransportMode: "Mode de transport du transporteur n°1",
  transporter1Type: "Type de transporteur n°1",
  transporter1OrgId: "Numéro d'identification du transporteur n°1",
  transporter1ReceiptNumber: "Numéro de récépissé du transporteur n°1",
  transporter1Name: "Raison sociale du transporteur n°1",
  transporter1Address: "Adresse du transporteur n°1",
  transporter1PostalCode: "Code postal du transporteur n°1",
  transporter1City: "Commune du transporteur n°1",
  transporter1CountryCode: "Code pays du transporteur n°1",
  transporter2TransportMode: "Mode de transport du transporteur n°2",
  transporter2Type: "Type de transporteur n°2",
  transporter2OrgId: "Numéro d'identification du transporteur n°2",
  transporter2ReceiptNumber: "Numéro de récépissé du transporteur n°2",
  transporter2Name: "Raison sociale du transporteur n°2",
  transporter2Address: "Adresse du transporteur n°2",
  transporter2PostalCode: "Code postal du transporteur n°2",
  transporter2City: "Commune du transporteur n°2",
  transporter2CountryCode: "Code pays du transporteur n°2",
  transporter3TransportMode: "Mode de transport du transporteur n°3",
  transporter3Type: "Type de transporteur n°3",
  transporter3OrgId: "Numéro d'identification du transporteur n°3",
  transporter3ReceiptNumber: "Numéro de récépissé du transporteur n°3",
  transporter3Name: "Raison sociale du transporteur n°3",
  transporter3Address: "Adresse du transporteur n°3",
  transporter3PostalCode: "Code postal du transporteur n°3",
  transporter3City: "Commune du transporteur n°3",
  transporter3CountryCode: "Code pays du transporteur n°3",
  transporter4TransportMode: "Mode de transport du transporteur n°4",
  transporter4Type: "Type de transporteur n°4",
  transporter4OrgId: "Numéro d'identification du transporteur n°4",
  transporter4ReceiptNumber: "Numéro de récépissé du transporteur n°4",
  transporter4Name: "Raison sociale du transporteur n°4",
  transporter4Address: "Adresse du transporteur n°4",
  transporter4PostalCode: "Code postal du transporteur n°4",
  transporter4City: "Commune du transporteur n°4",
  transporter4CountryCode: "Code pays du transporteur n°4",
  transporter5TransportMode: "Mode de transport du transporteur n°5",
  transporter5Type: "Type de transporteur n°5",
  transporter5OrgId: "Numéro d'identification du transporteur n°5",
  transporter5ReceiptNumber: "Numéro de récépissé du transporteur n°5",
  transporter5Name: "Raison sociale du transporteur n°5",
  transporter5Address: "Adresse du transporteur n°5",
  transporter5PostalCode: "Code postal du transporteur n°5",
  transporter5City: "Commune du transporteur n°5",
  transporter5CountryCode: "Code pays du transporteur n°5"
};
