ALTER TABLE  default$default."Bsvhu"
    ALTER COLUMN "emitterCompanyContact" TYPE text,
    ALTER COLUMN "emitterCompanyPhone" TYPE text,
    ALTER COLUMN "emitterCompanyMail" TYPE text,
    ALTER COLUMN "emitterEmissionSignatureAuthor" TYPE text,
    ALTER COLUMN "destinationCompanyContact" TYPE text,
    ALTER COLUMN "destinationCompanyPhone" TYPE text,
    ALTER COLUMN "destinationCompanyMail" TYPE text,
    ALTER COLUMN "transporterCompanyContact" TYPE text,
    ALTER COLUMN "transporterCompanyPhone" TYPE text,
    ALTER COLUMN "transporterCompanyMail" TYPE text,
    ALTER COLUMN "transporterRecepisseNumber" TYPE text,
    ALTER COLUMN "transporterRecepisseDepartment" TYPE text,
    ALTER COLUMN "transporterTransportSignatureAuthor" TYPE text,
    ALTER COLUMN "destinationOperationNextDestinationCompanyContact" TYPE text,
    ALTER COLUMN "destinationOperationNextDestinationCompanyPhone" TYPE text,
    ALTER COLUMN "destinationOperationNextDestinationCompanyMail" TYPE text,
    ALTER COLUMN "destinationOperationSignatureAuthor" TYPE text;
