web: node ${STARTUP_FILE:-dist/back/index.js}
clock: node dist/back/back/src/cron.js
queue: node dist/back/back/src/queue/consumer.js
indexqueue: node dist/back/back/src/queue/consumerIndexation.js
webhooksqueue: node dist/back/back/src/queue/consumerWebhooks.js
