
psql --username "$POSTGRES_USER" << EOF
  CREATE DATABASE airflow;
  CREATE USER $AIRFLOW_POSTGRES_USER WITH PASSWORD '$AIRFLOW_POSTGRES_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE airflow to $AIRFLOW_POSTGRES_USER;
  CREATE DATABASE etl;
EOF

psql --username "$POSTGRES_USER" -d etl << EOF
  CREATE EXTENSION postgis;
  CREATE SCHEMA etl;
EOF

