# Inspired from https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/docker-compose.yaml
name: otel-local
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command:
      [
        "--config=/etc/otelcol-config.yaml",
        "--config=/etc/otelcol-config.dev.yaml"
      ]
    volumes:
      - ../collector-config.yaml:/etc/otelcol-config.yaml
      - ./collector-config.dev.yaml:/etc/otelcol-config.dev.yaml
    ports:
      - 4317:4317 # OTLP grpc receiver
      - 4318:4318 # OTLP http receiver
    environment:
      - PORT=4318
      - OTEL_DB_ENDPOINT=localhost:5432
      - OTEL_DB_USER=trackdechets
      - OTEL_DB_PWD=password

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
      - "4318" # otlp http

  prometheus: # Temp writes metrics to Prometheus
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki.yaml"]
    user: "0"
    volumes:
      - ./loki.yaml:/etc/loki.yaml
      - ./loki-data:/tmp/loki
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:10.1.1
    volumes:
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3003:3000"
