# Inspired from https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/docker-compose.yaml
name: otel-local
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command:
      [
        "--config=/etc/otelcol-config.yaml",
        "--config=/etc/otelcol-config.dev.yaml"
      ]
    volumes:
      - ../collector-config.yaml:/etc/otelcol-config.yaml
      - ./collector-config.dev.yaml:/etc/otelcol-config.dev.yaml
    ports:
      - 4318:4318 # OTLP http receiver
    environment:
      - PORT=4318
      - OTEL_DB_ENDPOINT=localhost:5432
      - OTEL_DB_USER=trackdechets
      - OTEL_DB_PWD=password
