-- CreateTable
CREATE TABLE "RegistryOutgoingWaste" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "importId" TEXT,
    "isLatest" BOOLEAN NOT NULL DEFAULT true,
    "isCancelled" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT NOT NULL,
    "publicId" TEXT NOT NULL,
    "reportForCompanySiret" TEXT NOT NULL,
    "reportForCompanyName" TEXT NOT NULL,
    "reportForCompanyAddress" TEXT NOT NULL,
    "reportForCompanyCity" TEXT NOT NULL,
    "reportForCompanyPostalCode" TEXT NOT NULL,
    "reportForPickupSiteName" TEXT,
    "reportForPickupSiteAddress" TEXT,
    "reportForPickupSitePostalCode" TEXT,
    "reportForPickupSiteCity" TEXT,
    "reportForPickupSiteCountryCode" TEXT,
    "reportAsCompanySiret" TEXT,
    "wasteDescription" TEXT NOT NULL,
    "wasteCode" TEXT NOT NULL,
    "wasteCodeBale" TEXT,
    "wastePop" BOOLEAN NOT NULL,
    "wasteIsDangerous" BOOLEAN,
    "dispatchDate" TIMESTAMP(3),
    "weightValue" DOUBLE PRECISION NOT NULL,
    "weightIsEstimate" BOOLEAN NOT NULL,
    "volume" DOUBLE PRECISION,
    "initialEmitterCompanyType" TEXT NOT NULL,
    "initialEmitterCompanyOrgId" TEXT,
    "initialEmitterCompanyName" TEXT,
    "initialEmitterCompanyAddress" TEXT,
    "initialEmitterCompanyPostalCode" TEXT,
    "initialEmitterCompanyCity" TEXT,
    "initialEmitterCompanyCountryCode" TEXT,
    "initialEmitterMunicipalitiesInseeCodes" TEXT[],
    "initialEmitterMunicipalitiesNames" TEXT[],
    "destinationCompanyType" TEXT NOT NULL,
    "destinationCompanyOrgId" TEXT,
    "destinationCompanyName" TEXT,
    "destinationCompanyAddress" TEXT,
    "destinationCompanyCity" TEXT,
    "destinationCompanyPostalCode" TEXT,
    "destinationCompanyCountryCode" TEXT,
    "destinationDropSiteAddress" TEXT,
    "destinationDropSitePostalCode" TEXT,
    "destinationDropSiteCity" TEXT,
    "destinationDropSiteCountryCode" TEXT,
    "declarationNumber" TEXT,
    "notificationNumber" TEXT,
    "movementNumber" TEXT,
    "operationCode" TEXT NOT NULL,
    "operationMode" "OperationMode",
    "ecoOrganismeSiret" TEXT,
    "ecoOrganismeName" TEXT,
    "brokerCompanySiret" TEXT,
    "brokerCompanyName" TEXT,
    "brokerRecepisseNumber" TEXT,
    "traderCompanySiret" TEXT,
    "traderCompanyName" TEXT,
    "traderRecepisseNumber" TEXT,
    "isDirectSupply" BOOLEAN,
    "transporter1TransportMode" "TransportMode",
    "transporter1CompanyType" TEXT,
    "transporter1CompanyOrgId" TEXT,
    "transporter1RecepisseIsExempted" BOOLEAN,
    "transporter1RecepisseNumber" TEXT,
    "transporter1CompanyName" TEXT,
    "transporter1CompanyAddress" TEXT,
    "transporter1CompanyPostalCode" TEXT,
    "transporter1CompanyCity" TEXT,
    "transporter1CompanyCountryCode" TEXT,
    "transporter2TransportMode" "TransportMode",
    "transporter2CompanyType" TEXT,
    "transporter2CompanyOrgId" TEXT,
    "transporter2RecepisseIsExempted" BOOLEAN,
    "transporter2RecepisseNumber" TEXT,
    "transporter2CompanyName" TEXT,
    "transporter2CompanyAddress" TEXT,
    "transporter2CompanyPostalCode" TEXT,
    "transporter2CompanyCity" TEXT,
    "transporter2CompanyCountryCode" TEXT,
    "transporter3TransportMode" "TransportMode",
    "transporter3CompanyType" TEXT,
    "transporter3CompanyOrgId" TEXT,
    "transporter3RecepisseIsExempted" BOOLEAN,
    "transporter3RecepisseNumber" TEXT,
    "transporter3CompanyName" TEXT,
    "transporter3CompanyAddress" TEXT,
    "transporter3CompanyPostalCode" TEXT,
    "transporter3CompanyCity" TEXT,
    "transporter3CompanyCountryCode" TEXT,
    "transporter4TransportMode" "TransportMode",
    "transporter4CompanyType" TEXT,
    "transporter4CompanyOrgId" TEXT,
    "transporter4RecepisseIsExempted" BOOLEAN,
    "transporter4RecepisseNumber" TEXT,
    "transporter4CompanyName" TEXT,
    "transporter4CompanyAddress" TEXT,
    "transporter4CompanyPostalCode" TEXT,
    "transporter4CompanyCity" TEXT,
    "transporter4CompanyCountryCode" TEXT,
    "transporter5TransportMode" "TransportMode",
    "transporter5CompanyType" TEXT,
    "transporter5CompanyOrgId" TEXT,
    "transporter5RecepisseIsExempted" BOOLEAN,
    "transporter5RecepisseNumber" TEXT,
    "transporter5CompanyName" TEXT,
    "transporter5CompanyAddress" TEXT,
    "transporter5CompanyPostalCode" TEXT,
    "transporter5CompanyCity" TEXT,
    "transporter5CompanyCountryCode" TEXT,

    CONSTRAINT "RegistryOutgoingWaste_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "_RegistryOutgoingWasteImportIdIdx" ON "RegistryOutgoingWaste"("importId");

-- CreateIndex
CREATE INDEX "_RegistryOutgoingWastePublicIdReportForCompanySiretIdx" ON "RegistryOutgoingWaste"("publicId", "reportForCompanySiret");

-- AddForeignKey
ALTER TABLE "RegistryOutgoingWaste" ADD CONSTRAINT "RegistryOutgoingWaste_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
