version: "3"

services:
  postgres:
    image: postgres:10.5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    restart: always

  cachet:
    image: cachethq/docker:2.3.15
    ports:
      - 81:8000
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure

  monitor:
    build:
      context: ./monitor
    volumes:
      - ./monitor/config.json:/etc/cachet-monitor.config.json
    depends_on:
      - cachet
    restart: on-failure


volumes:
  postgres:

