import { ParsedZodInputOutgoingWasteItem } from "./validation/schema";

export const OUTGOING_WASTE_HEADERS: {
  [key in keyof ParsedZodInputOutgoingWasteItem]: string;
} = {
  reason: "Motif",
  publicId: "Identifiant unique",
  reportAsCompanySiret: "SIRET du déclarant",
  reportForCompanySiret: "SIRET de l'expéditeur ou du détenteur",
  reportForPickupSiteName:
    "Référence du chantier ou du lieu de collecte de l'expéditeur ou du détenteur",
  reportForPickupSiteAddress:
    "Libellé de l'adresse du chantier ou du lieu de collecte de l'expéditeur ou du détenteur",
  reportForPickupSitePostalCode:
    "Code postal du chantier ou du lieu de collecte de l'expéditeur ou du détenteur",
  reportForPickupSiteCity:
    "Commune du chantier ou du lieu de collecte de l'expéditeur ou du détenteur",
  reportForPickupSiteCountryCode:
    "Code pays du chantier ou du lieu de collecte de l'expéditeur ou du détenteur",
  wasteDescription: "Dénomination du déchet",
  wasteCode: "Code déchet",
  wasteCodeBale: "Code déchet Bâle",
  wastePop: "POP",
  wasteIsDangerous: "Dangereux",
  dispatchDate: "Date d'expédition",
  weightValue: "Poids en tonnes",
  weightIsEstimate: "Type de poids",
  volume: "Volume en M3",
  initialEmitterCompanyType: "Type de producteur initial",
  initialEmitterCompanyOrgId: "Numéro d'identification du producteur initial",
  initialEmitterCompanyName: "Raison sociale du producteur initial",
  initialEmitterCompanyAddress: "Libellé de l'adresse du producteur initial",
  initialEmitterCompanyPostalCode: "Code postal du producteur initial",
  initialEmitterCompanyCity: "Commune du producteur initial",
  initialEmitterCompanyCountryCode: "Code pays du producteur initial",
  initialEmitterMunicipalitiesInseeCodes: "Code(s) INSEE de(s) commune(s)",
  initialEmitterMunicipalitiesNames: "Commune(s)",
  destinationCompanyType: "Type de destinataire",
  destinationCompanyOrgId: "Numéro d'identification du destinataire",
  destinationCompanyName: "Raison sociale du destinataire",
  destinationCompanyAddress: "Libellé de l'adresse du destinataire",
  destinationCompanyPostalCode: "Code postal du destinataire",
  destinationCompanyCity: "Commune du destinataire",
  destinationCompanyCountryCode: "Code pays du destinataire",
  destinationDropSiteAddress: "Libellé de l'adresse de dépôt du destinataire",
  destinationDropSitePostalCode: "Code postal du lieu de dépôt du destinataire",
  destinationDropSiteCity: "Commune du lieu de dépôt du destinataire",
  destinationDropSiteCountryCode: "Code pays du lieu de dépôt du destinataire",
  declarationNumber: "Numéro de déclaration GISTRID",
  notificationNumber: "Numéro de notification GISTRID",
  movementNumber: "Numéro de mouvement",
  operationCode: "Code de traitement prévu",
  operationMode: "Mode de traitement prévu",
  ecoOrganismeSiret: "SIRET de l'éco-organisme",
  ecoOrganismeName: "Raison sociale de l’éco-organisme ",
  brokerCompanySiret: "SIRET du courtier",
  brokerCompanyName: "Raison sociale du courtier",
  brokerRecepisseNumber: "Numéro de récépissé du courtier",
  traderCompanySiret: "SIRET du négociant",
  traderCompanyName: "Raison sociale du négociant",
  traderRecepisseNumber: "Numéro de récépissé du négociant",
  isDirectSupply: "Approvisionnement direct (pipeline, convoyeur)",
  transporter1TransportMode: "Mode de transport du transporteur n°1",
  transporter1CompanyType: "Type de transporteur n°1",
  transporter1CompanyOrgId: "Numéro d'identification du transporteur n°1",
  transporter1RecepisseIsExempted: "Raison sociale du transporteur n°1",
  transporter1RecepisseNumber: "Libellé de l'Adresse du transporteur n°1",
  transporter1CompanyName: "Code postal du transporteur n°1",
  transporter1CompanyAddress: "Commune du transporteur n°1",
  transporter1CompanyPostalCode: "Code pays du transporteur n°1",
  transporter1CompanyCity: "Exemption de récépissé du transporteur n°1",
  transporter1CompanyCountryCode: "Numéro de récépissé du transporteur n°1",
  transporter2TransportMode: "Mode de transport du transporteur n°2",
  transporter2CompanyType: "Type de transporteur n°2",
  transporter2CompanyOrgId: "Numéro d'identification du transporteur n°2",
  transporter2RecepisseIsExempted: "Raison sociale du transporteur n°2",
  transporter2RecepisseNumber: "Libellé de l'Adresse du transporteur n°2",
  transporter2CompanyName: "Code postal du transporteur n°2",
  transporter2CompanyAddress: "Commune du transporteur n°2",
  transporter2CompanyPostalCode: "Code pays du transporteur n°2",
  transporter2CompanyCity: "Exemption de récépissé du transporteur n°2",
  transporter2CompanyCountryCode: "Numéro de récépissé du transporteur n°2",
  transporter3TransportMode: "Mode de transport du transporteur n°3",
  transporter3CompanyType: "Type de transporteur n°3",
  transporter3CompanyOrgId: "Numéro d'identification du transporteur n°3",
  transporter3RecepisseIsExempted: "Raison sociale du transporteur n°3",
  transporter3RecepisseNumber: "Libellé de l'Adresse du transporteur n°3",
  transporter3CompanyName: "Code postal du transporteur n°3",
  transporter3CompanyAddress: "Commune du transporteur n°3",
  transporter3CompanyPostalCode: "Code pays du transporteur n°3",
  transporter3CompanyCity: "Exemption de récépissé du transporteur n°3",
  transporter3CompanyCountryCode: "Numéro de récépissé du transporteur n°3",
  transporter4TransportMode: "Mode de transport du transporteur n°4",
  transporter4CompanyType: "Type de transporteur n°4",
  transporter4CompanyOrgId: "Numéro d'identification du transporteur n°4",
  transporter4RecepisseIsExempted: "Raison sociale du transporteur n°4",
  transporter4RecepisseNumber: "Libellé de l'Adresse du transporteur n°4",
  transporter4CompanyName: "Code postal du transporteur n°4",
  transporter4CompanyAddress: "Commune du transporteur n°4",
  transporter4CompanyPostalCode: "Code pays du transporteur n°4",
  transporter4CompanyCity: "Exemption de récépissé du transporteur n°4",
  transporter4CompanyCountryCode: "Numéro de récépissé du transporteur n°4",
  transporter5TransportMode: "Mode de transport du transporteur n°5",
  transporter5CompanyType: "Type de transporteur n°5",
  transporter5CompanyOrgId: "Numéro d'identification du transporteur n°5",
  transporter5RecepisseIsExempted: "Raison sociale du transporteur n°5",
  transporter5RecepisseNumber: "Libellé de l'Adresse du transporteur n°5",
  transporter5CompanyName: "Code postal du transporteur n°5",
  transporter5CompanyAddress: "Commune du transporteur n°5",
  transporter5CompanyPostalCode: "Code pays du transporteur n°5",
  transporter5CompanyCity: "Exemption de récépissé du transporteur n°5",
  transporter5CompanyCountryCode: "Numéro de récépissé du transporteur n°5"
};
