version: "3"
services:
  td-api:
    image: td-api
    build: DockerfileApi.dev
    volumes:
      - ../../back:/usr/src/app
    env_file:
      - .cypress-tests-env
    ports:
      - 4000:4000
    depends_on:
      - redis
      - postgres
      - elasticsearch

  td-ui:
    stdin_open: true
    image: node:14.15.4
    working_dir: /usr/src/front
    command: sh -c "npm install && npm run dev"
    expose:
      - "3000"
    volumes:
      - ..:/usr/src/front
      - ../../back/src:/usr/src/back/src
    ports:
      - 3000:3000
    env_file:
      - .cypress-tests-env
    depends_on:
      - td-api

  postgres:
    image: circleci/postgres:12-alpine-ram
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: trackdechets
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    shm_size: "512m"

  redis:
    image: redis:5.0-alpine
    sysctls:
      - net.core.somaxconn=511
    ports:
      - 6379:6379


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
