import { ParsedZodInputManagedItem } from "./validation/schema";

export const MANAGED_HEADERS: {
  [key in keyof ParsedZodInputManagedItem]: string;
} = {
  reason: "Motif",
  publicId: "Identifiant unique",
  reportAsCompanySiret: "SIRET du déclarant",
  reportForCompanySiret: "SIRET du courtier ou négociant",
  wasteDescription: "Dénomination du déchet",
  wasteCode: "Code déchet",
  wasteCodeBale: "Code déchet Bâle",
  wastePop: "POP",
  wasteIsDangerous: "Dangereux",
  managingStartDate: "Date d'acquisition ou de début de gestion",
  managingEndDate: "Date de cession ou de fin de gestion",
  weightValue: "Poids en tonnes",
  weightIsEstimate: "Type de poids",
  volume: "Volume en M3",
  wasteDap: "DAP",
  initialEmitterCompanyType: "Type de producteur initial",
  initialEmitterCompanyOrgId: "Numéro d'identification du producteur initial",
  initialEmitterCompanyName: "Raison sociale du producteur initial",
  initialEmitterCompanyAddress: "Libellé de l'adresse du producteur initial",
  initialEmitterCompanyPostalCode: "Code postal du producteur initial",
  initialEmitterCompanyCity: "Commune du producteur initial",
  initialEmitterCompanyCountryCode: "Code pays du producteur initial",
  initialEmitterMunicipalitiesInseeCodes: "Code(s) INSEE de(s) commune(s)",
  initialEmitterMunicipalitiesNames: "Commune(s)",
  parcelInseeCodes: "Codes INSEE des parcelles",
  parcelNumbers: "Numéro(s) des parcelles",
  parcelCoordinates: "Coordonnées des parcelles",
  sisIdentifier: "Identifiant SIS du terrain",
  emitterCompanyType: "Type d'expéditeur ou de remettant",
  emitterCompanyOrgId:
    "Numéro d'identification de l'expéditeur ou du remettant",
  emitterCompanyName: "Raison sociale de l'expéditeur ou du remettant",
  emitterCompanyAddress: "Libellé de l'adresse de l'expéditeur ou du remettant",
  emitterCompanyPostalCode: "Code postal de l'expéditeur ou du remettant",
  emitterCompanyCity: "Commune de l'expéditeur ou du remettant",
  emitterCompanyCountryCode: "Code pays de l'expéditeur ou du remettant",
  emitterPickupSiteName:
    "Référence du chantier ou du lieu de collecte de l'expéditeur ou du remettant",
  emitterPickupSiteAddress:
    "Libellé de l'adresse du chantier ou du lieu de collecte de l'expéditeur ou du remettant",
  emitterPickupSitePostalCode:
    "Code postal du chantier ou du lieu de collecte de l'expéditeur ou du remettant",
  emitterPickupSiteCity:
    "Commune du chantier ou du lieu de collecte de l'expéditeur ou du remettant",
  emitterPickupSiteCountryCode:
    "Code pays du chantier ou du lieu de collecte de l'expéditeur ou du remettant",
  tempStorerCompanyType: "Type d'installation de Tri Transit Regroupement",
  tempStorerCompanyOrgId:
    "Numéro d'identification de l'installation de Tri Transit Regroupement",
  tempStorerCompanyName:
    "Raison sociale de l'installation de Tri Transit Regroupement",
  tempStorerCompanyAddress:
    "Libellé de l'adresse de l'installation de Tri Transit Regroupement",
  tempStorerCompanyPostalCode:
    "Code postal de l'installation de Tri Transit Regroupement",
  tempStorerCompanyCity:
    "Commune de l'installation de Tri Transit Regroupement",
  tempStorerCompanyCountryCode:
    "Code pays de l'installation de Tri Transit Regroupement",
  destinationCompanyType: "Type de destinataire",
  destinationCompanyOrgId: "Numéro d'identification du destinataire",
  destinationCompanyName: "Raison sociale du destinataire",
  destinationCompanyAddress: "Libellé de l'adresse du destinataire",
  destinationCompanyPostalCode: "Code postal du destinataire",
  destinationCompanyCity: "Commune du destinataire",
  destinationCompanyCountryCode: "Code pays du destinataire",
  destinationDropSiteAddress: "Libellé de l'adresse de dépôt du destinataire",
  destinationDropSitePostalCode: "Code postal du lieu de dépôt du destinataire",
  destinationDropSiteCity: "Commune du lieu de dépôt du destinataire",
  destinationDropSiteCountryCode: "Code pays du lieu de dépôt du destinataire",
  declarationNumber: "Numéro de déclaration GISTRID",
  notificationNumber: "Numéro de notification GISTRID",
  movementNumber: "Numéro de mouvement",
  operationCode: "Code de traitement prévu",
  operationMode: "Mode de traitement prévu",
  isUpcycled: "Terres valorisées",
  destinationParcelInseeCodes: "Codes INSEE des parcelles si valorisation",
  destinationParcelNumbers: "Numéro(s) des parcelles si valorisation",
  destinationParcelCoordinates: "Coordonnées des parcelles si valorisation",
  ecoOrganismeSiret: "SIRET de l'éco-organisme",
  ecoOrganismeName: "Raison sociale de l'éco-organisme",
  isDirectSupply: "Approvisionnement direct",
  transporter1TransportMode: "Mode de transport du transporteur n°1",
  transporter1CompanyType: "Type de transporteur n°1",
  transporter1CompanyOrgId: "Numéro d'identification du transporteur n°1",
  transporter1CompanyName: "Raison sociale du transporteur n°1",
  transporter1CompanyAddress: "Libellé de l'adresse du transporteur n°1",
  transporter1CompanyPostalCode: "Code postal du transporteur n°1",
  transporter1CompanyCity: "Commune du transporteur n°1",
  transporter1CompanyCountryCode: "Code pays du transporteur n°1",
  transporter1RecepisseIsExempted: "Exemption de récépissé du transporteur n°1",
  transporter1RecepisseNumber: "Numéro de récépissé du transporteur n°1",
  transporter2TransportMode: "Mode de transport du transporteur n°2",
  transporter2CompanyType: "Type de transporteur n°2",
  transporter2CompanyOrgId: "Numéro d'identification du transporteur n°2",
  transporter2CompanyName: "Raison sociale du transporteur n°2",
  transporter2CompanyAddress: "Libellé de l'adresse du transporteur n°2",
  transporter2CompanyPostalCode: "Code postal du transporteur n°2",
  transporter2CompanyCity: "Commune du transporteur n°2",
  transporter2CompanyCountryCode: "Code pays du transporteur n°2",
  transporter2RecepisseIsExempted: "Exemption de récépissé du transporteur n°2",
  transporter2RecepisseNumber: "Numéro de récépissé du transporteur n°2",
  transporter3TransportMode: "Mode de transport du transporteur n°3",
  transporter3CompanyType: "Type de transporteur n°3",
  transporter3CompanyOrgId: "Numéro d'identification du transporteur n°3",
  transporter3CompanyName: "Raison sociale du transporteur n°3",
  transporter3CompanyAddress: "Libellé de l'adresse du transporteur n°3",
  transporter3CompanyPostalCode: "Code postal du transporteur n°3",
  transporter3CompanyCity: "Commune du transporteur n°3",
  transporter3CompanyCountryCode: "Code pays du transporteur n°3",
  transporter3RecepisseIsExempted: "Exemption de récépissé du transporteur n°3",
  transporter3RecepisseNumber: "Numéro de récépissé du transporteur n°3",
  transporter4TransportMode: "Mode de transport du transporteur n°4",
  transporter4CompanyType: "Type de transporteur n°4",
  transporter4CompanyOrgId: "Numéro d'identification du transporteur n°4",
  transporter4CompanyName: "Raison sociale du transporteur n°4",
  transporter4CompanyAddress: "Libellé de l'adresse du transporteur n°4",
  transporter4CompanyPostalCode: "Code postal du transporteur n°4",
  transporter4CompanyCity: "Commune du transporteur n°4",
  transporter4CompanyCountryCode: "Code pays du transporteur n°4",
  transporter4RecepisseIsExempted: "Exemption de récépissé du transporteur n°4",
  transporter4RecepisseNumber: "Numéro de récépissé du transporteur n°4",
  transporter5TransportMode: "Mode de transport du transporteur n°5",
  transporter5CompanyType: "Type de transporteur n°5",
  transporter5CompanyOrgId: "Numéro d'identification du transporteur n°5",
  transporter5CompanyName: "Raison sociale du transporteur n°5",
  transporter5CompanyAddress: "Libellé de l'adresse du transporteur n°5",
  transporter5CompanyPostalCode: "Code postal du transporteur n°5",
  transporter5CompanyCity: "Commune du transporteur n°5",
  transporter5CompanyCountryCode: "Code pays du transporteur n°5",
  transporter5RecepisseIsExempted: "Exemption de récépissé du transporteur n°5",
  transporter5RecepisseNumber: "Numéro de récépissé du transporteur n°5"
};
