import fs from "fs";
import path from "path";
import { Job } from "bull";
import { CompanyType } from "@prisma/client";
import prisma from "../../prisma";
import { searchCompany } from "../../companies/search";
import { CompanySearchResult } from "../../companies/types";
import { ApiResponse, Client, estypes } from "@elastic/elasticsearch";
import { FavoriteType } from "../../generated/graphql/types";
import { getTransporterCompanyOrgId } from "../../common/constants/companySearchHelpers";
import { getCompanyOrCompanyNotFound } from "../../companies/database";
import { SearchResponse } from "@elastic/elasticsearch/api/types";
import { BsdElastic, index } from "../../common/elastic";

export interface FavoriteIndexBody {
  favorites: CompanySearchResult[];
  orgId: string;
  type: FavoriteType;
}

// Required because FavoriteType is generated by graphql-codegen as a type
export const allFavoriteTypes: FavoriteType[] = [
  "BROKER",
  "DESTINATION",
  "EMITTER",
  "NEXT_DESTINATION",
  "RECIPIENT",
  "TEMPORARY_STORAGE_DETAIL",
  "TRADER",
  "TRANSPORTER",
  "WORKER"
];

/**
 * ElasticSearch Favorites index
 */
export const indexConfig = {
  // Do not change this alias name unless you know what you do
  alias: process.env.ELASTIC_SEARCH_FAVORITES_ALIAS || "favorites",
  url: process.env.ELASTIC_SEARCH_URL || "http://elasticsearch:9200/"
};

/**
 * es.cert is the private CA key from the ElasticSearch hosting
 * if absent, either the CA is public, either url uses http
 */
const certPath = path.join(__dirname, "es.cert");

let ssl;

if (fs.existsSync(certPath)) {
  ssl = { ca: fs.readFileSync(certPath, "utf-8") };
} else if (process.env.ELASTICSEARCH_FAVORITES_CACERT) {
  ssl = { ca: process.env.ELASTICSEARCH_FAVORITES_CACERT };
}

// bypass ssl verif
if (!!ssl && process.env.ELASTICSEARCH_FAVORITES_IGNORE_SSL === "true") {
  ssl.rejectUnauthorized = false;
}

export const client = new Client({
  node: indexConfig.url,
  ssl
});

export interface FavoritesInput {
  orgId: string;
  type: FavoriteType;
}

const MAX_FAVORITES = 10;

function matchesFavoriteType(
  companyTypes: CompanyType[],
  favoriteType: FavoriteType
): boolean {
  const EMITTER: CompanyType[] = ["PRODUCER", "ECO_ORGANISME"];
  const TRANSPORTER: CompanyType[] = ["TRANSPORTER"];
  const TRADER: CompanyType[] = ["TRADER"];
  const BROKER: CompanyType[] = ["BROKER"];
  const RECIPIENT: CompanyType[] = [
    "COLLECTOR",
    "WASTEPROCESSOR",
    "WASTE_VEHICLES",
    "WASTE_CENTER"
  ];
  const WORKER: CompanyType[] = ["PRODUCER"];
  const DESTINATION = RECIPIENT;
  const NEXT_DESTINATION = RECIPIENT;
  const TEMPORARY_STORAGE_DETAIL = RECIPIENT;

  const COMPANY_CONSTANTS: Record<FavoriteType, CompanyType[]> = {
    EMITTER,
    TRANSPORTER,
    TRADER,
    BROKER,
    RECIPIENT,
    DESTINATION,
    NEXT_DESTINATION,
    TEMPORARY_STORAGE_DETAIL,
    WORKER
  };

  return COMPANY_CONSTANTS[favoriteType].some(matchingCompanyType =>
    companyTypes.includes(matchingCompanyType)
  );
}

async function getRecentEmitters(
  orgId: string,
  defaultWhere: estypes.QueryContainer
): Promise<CompanySearchResult[]> {
  const { body }: ApiResponse<SearchResponse<BsdElastic>> = await client.search(
    {
      index: index.alias,
      body: {
        size: MAX_FAVORITES,
        ...{
          ...defaultWhere,
          ...{
            must: {
              emitterCompanySiret: orgId
            }
          }
        }
      }
    }
  );
  const hits = body.hits.hits.slice(0, MAX_FAVORITES);
  const emitterSirets = [
    ...new Set(hits.map(f => f._source?.emitterCompanySiret).filter(Boolean))
  ];
  const favorites = await Promise.all(
    emitterSirets.map(async siret => {
      try {
        return await searchCompany(siret);
      } catch (_) {
        return null;
      }
    })
  );

  return favorites.filter(Boolean);
}

async function getRecentRecipients(
  orgId: string,
  defaultWhere: estypes.QueryContainer
): Promise<CompanySearchResult[]> {
  const { body }: ApiResponse<SearchResponse<BsdElastic>> = await client.search(
    {
      index: index.alias,
      body: {
        size: MAX_FAVORITES,
        ...{
          ...defaultWhere,
          ...{
            must: {
              destinationCompanySiret: orgId
            }
          }
        }
      }
    }
  );
  const hits = body.hits.hits.slice(0, MAX_FAVORITES);
  const destinationSirets = [
    ...new Set(
      hits.map(f => f._source?.destinationCompanySiret).filter(Boolean)
    )
  ];
  const favorites = await Promise.all(
    destinationSirets.map(async siret => {
      try {
        return await searchCompany(siret);
      } catch (_) {
        return null;
      }
    })
  );

  return favorites.filter(Boolean);
}

async function getRecentNextDestinations(
  orgId: string,
  defaultWhere: estypes.QueryContainer
) {
  const { body }: ApiResponse<SearchResponse<BsdElastic>> = await client.search(
    {
      index: index.alias,
      body: {
        size: MAX_FAVORITES,
        ...{
          ...defaultWhere,
          ...{
            must: {
              nextDestinationCompanySiret: orgId
            }
          }
        }
      }
    }
  );
  const hits = body.hits.hits.slice(0, MAX_FAVORITES);
  const nextDestinationSirets = [
    ...new Set(
      hits.map(f => f._source?.nextDestinationCompanySiret).filter(Boolean)
    )
  ];

  const favorites = await Promise.all(
    nextDestinationSirets.map(async siret => {
      try {
        return await searchCompany(siret);
      } catch (_) {
        return null;
      }
    })
  );

  return favorites.filter(Boolean);
}

/**
 * Only retrieve the first Transporter if many exists
 */
async function getRecentTransporters(
  orgId: string,
  defaultWhere: estypes.QueryContainer
) {
  const { body }: ApiResponse<SearchResponse<BsdElastic>> = await client.search(
    {
      index: index.alias,
      body: {
        size: MAX_FAVORITES,
        ...{
          ...defaultWhere,
          ...{
            should: {
              transporterCompanySiret: orgId,
              transporterCompanyVatNumber: orgId
            }
          }
        }
      }
    }
  );
  const hits = body.hits.hits.slice(0, MAX_FAVORITES);
  const transporterOrgIds = [
    ...new Set(
      hits
        .map(f => (f._source ? getTransporterCompanyOrgId(f._source) : null))
        .filter(Boolean)
    )
  ];

  const favorites = await Promise.all(
    transporterOrgIds.map(async orgId => {
      try {
        return await searchCompany(orgId);
      } catch (_) {
        return null;
      }
    })
  );

  return favorites.filter(Boolean);
}

async function getRecentTraders(
  orgId: string,
  defaultWhere: estypes.QueryContainer
): Promise<CompanySearchResult[]> {
  const { body }: ApiResponse<SearchResponse<BsdElastic>> = await client.search(
    {
      index: index.alias,
      body: {
        size: MAX_FAVORITES,
        ...{
          ...defaultWhere,
          ...{
            must: {
              traderCompanySiret: orgId
            }
          }
        }
      }
    }
  );
  const hits = body.hits.hits.slice(0, MAX_FAVORITES);
  const traderSirets = [
    ...new Set(hits.map(f => f._source?.traderCompanySiret).filter(Boolean))
  ];
  const favorites = await Promise.all(
    traderSirets.map(async siret => {
      try {
        const favorite = await searchCompany(siret);
        const traderReceipt = await prisma.company
          .findUnique({
            where: { orgId: favorite.orgId }
          })
          .traderReceipt();
        return { ...favorite, traderReceipt };
      } catch (_) {
        return null;
      }
    })
  );

  return favorites.filter(Boolean);
}

async function getRecentBrokers(
  orgId: string,
  defaultWhere: estypes.QueryContainer
): Promise<CompanySearchResult[]> {
  const { body }: ApiResponse<SearchResponse<BsdElastic>> = await client.search(
    {
      index: index.alias,
      body: {
        size: MAX_FAVORITES,
        ...{
          ...defaultWhere,
          ...{
            must: {
              brokerCompanySiret: orgId
            }
          }
        }
      }
    }
  );

  const hits = body.hits.hits.slice(0, MAX_FAVORITES);
  const brokerSirets = [
    ...new Set(hits.map(f => f._source?.brokerCompanySiret).filter(Boolean))
  ];

  const favorites = await Promise.all(
    brokerSirets.map(async siret => {
      try {
        const favorite = await searchCompany(siret);
        const brokerReceipt = await prisma.company
          .findUnique({
            where: { orgId: favorite.orgId }
          })
          .brokerReceipt();
        return { ...favorite, brokerReceipt };
      } catch (_) {
        return null;
      }
    })
  );

  return favorites.filter(Boolean);
}

/**
 * Return a list of companies the user (and their company) have been working with recently.
 * The list is filtered according to a given "FavoriteType": a field of the form.
 *
 * For emitter, transporter, and destination after temporary storage, we only return companies registered in TD
 * For brokers, traders, and next destinations we only returns companies present in SIRENE database
 *
 * @param {string} siret SIRET of the company for which to retrieve the recent partners
 * @param {FavoriteType} type the type of partners to search for
 *
 * @returns {Promise} resolves to a list of recent partners matching the provided parameters
 */
async function getRecentPartners(
  orgId: string,
  type: FavoriteType
): Promise<CompanySearchResult[]> {
  const defaultFilter: estypes.QueryContainer = {
    bool: {
      must_not: [{ term: { status: "DRAFT" } }]
    }
  };
  switch (type) {
    case "EMITTER":
      return getRecentEmitters(orgId, defaultFilter);
    case "TRANSPORTER":
      return getRecentTransporters(orgId, defaultFilter);
    case "TEMPORARY_STORAGE_DETAIL":
    case "RECIPIENT":
    case "DESTINATION":
      return getRecentRecipients(orgId, defaultFilter);
    case "NEXT_DESTINATION":
      return getRecentNextDestinations(orgId, defaultFilter);
    case "BROKER":
      return getRecentBrokers(orgId, defaultFilter);
    case "TRADER":
      return getRecentTraders(orgId, defaultFilter);
    default:
      return [];
  }
}

export const favoritesConstrutor = async ({
  orgId,
  type
}: FavoritesInput): Promise<CompanySearchResult[]> => {
  const company = await getCompanyOrCompanyNotFound({ orgId });
  const favorites = company.orgId
    ? await getRecentPartners(company.orgId, type)
    : [];

  // return early
  if (favorites.length + 1 >= MAX_FAVORITES) {
    favorites.splice(MAX_FAVORITES);
    return favorites;
  }

  // the user's company matches the provided favorite type
  const isMatchingType = matchesFavoriteType(company.companyTypes, type);
  // their company is not included in the results yet
  const isAlreadyListed = favorites.find(
    favorite => favorite.orgId === company.orgId
  );
  if (isMatchingType && !isAlreadyListed) {
    const companySearch = await searchCompany(company.orgId);
    favorites.push(companySearch);
  }

  // Return up to MAX_FAVORITES results
  favorites.splice(MAX_FAVORITES);
  return favorites;
};

/**
 * ElasticSearhc identifier constructor
 */
export function getIndexFavoritesId({ orgId, type }: FavoritesInput) {
  return `${orgId}-${type}`;
}

/**
 * Create/update a favorite in Elastic Search.
 */
export function indexFavorites(
  favorites: CompanySearchResult[],
  { orgId, type }: FavoritesInput
) {
  return client.index(
    {
      index: indexConfig.alias,
      id: getIndexFavoritesId({ orgId, type }),
      body: {
        favorites,
        orgId,
        type
      } as FavoriteIndexBody
    },
    {
      // do not throw version conflict errors
      ignore: [409]
    }
  );
}

export const indexFavoritesJob = async (job: Job<FavoritesInput>) => {
  const { orgId, type } = job.data;

  try {
    // Index the companies in Elasticsearch
    return indexFavorites(await favoritesConstrutor({ orgId, type }), {
      orgId,
      type
    });
  } catch (error) {
    console.error(error);
    throw new Error(
      "An error occurred while indexing the favorite in Elasticsearch"
    );
  }
};
