site_name: Trackdéchets
site_description: Gérer la traçabilité des déchets en toute sécurité.
site_author: Orion Charlier
site_url: https://trackdechets.beta.gouv.fr/

repo_url: https://github.com/MTES-MCT/trackdechets
theme: readthedocs
markdown_extensions:
  - admonition
nav:
  - "Introduction": "index.md"
  - "Informations sur l'interopérabilité": "infos.md"
  - "Mise en route": "getting-started.md"
  - "Cycle de vie d'un BSD": "workflow.md"
  - "Cas d'usages": "use-cases.md"
  - "Gestion des erreurs": "errors.md"
  - "Lexique": "glossary.md"
  - "OAuth2": "oauth2.md"
  - "Playground": "playground.md"
  - "Référence de l'API": "api-reference/api-reference.md"
  - "Changelog": "changelog.md"

