site_name: Trackdéchets
site_description: Gérer la traçabilité des déchets en toute sécurité.
site_author: Orion Charlier
site_url: https://trackdechets.beta.gouv.fr/

repo_url: https://github.com/MTES-MCT/trackdechets
theme: readthedocs
markdown_extensions:
  - admonition
nav:
  - "Introduction": "index.md"
  - "Faire des appels à l'API GraphQL": "graphql.md"
  - "Cycle de vie des BSD's": "workflow.md"
  - "Gestion des erreurs": "errors.md"
  - "OAuth2": "oauth2.md"
  - "Les environnements de tests": "environments.md"
  - "Obtenir un jeton d'accès personnel": "access-token.md"
  - "Playground": "playground.md"
  - "Référence de l'API": "api-reference/api-reference.md"
  - "Changelog": "changelog.md"

