-- Those are the NON BREAKING changes generated by the Prisma upgrade CLI
-- Note: some manual adjustements had to be made. The auto generated statements had a few incompatibilities.

-- Add missing `DEFAULT` constraints to the database
-- https://pris.ly/d/schema-incompatibilities#default-values-arent-represented-in-database

ALTER TABLE "default$default"."Form" ALTER COLUMN "isDeleted" SET DEFAULT false;
ALTER TABLE "default$default"."Form" ALTER COLUMN "isImportedFromPaper" SET DEFAULT false;
ALTER TABLE "default$default"."Form" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "default$default"."Form" ALTER COLUMN "recipientIsTempStorage" SET DEFAULT false;
ALTER TABLE "default$default"."TemporaryStorageDetail" ALTER COLUMN "destinationIsFilledByEmitter" SET DEFAULT true;
ALTER TABLE "default$default"."TransportSegment" ALTER COLUMN "readyToTakeOver" SET DEFAULT false;
ALTER TABLE "default$default"."User" ALTER COLUMN "isActive" SET DEFAULT false;
ALTER TABLE "default$default"."MembershipRequest" ALTER COLUMN "status" SET DEFAULT 'PENDING';
ALTER TABLE "default$default"."AccessToken" ALTER COLUMN "isRevoked" SET DEFAULT false;


-- Replicate `@createdAt` behavior in Prisma 2
-- https://pris.ly/d/schema-incompatibilities#createdat-isnt-represented-in-database

ALTER TABLE "default$default"."Form" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."TransportSegment" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."User" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."UserActivationHash" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."UserAccountHash" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."MembershipRequest" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."AccessToken" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."Application" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."Grant" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "default$default"."Company" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;


-- Fix 1-1 relations by adding `UNIQUE` constraints
-- https://pris.ly/d/schema-incompatibilities#inline-1-1-relations-are-recognized-as-1-n-missing-unique-constraint

ALTER TABLE "default$default"."Form" ADD UNIQUE ("temporaryStorageDetail");


-- Migrate IDs from varchar(25) to varchar(30)
-- https://pris.ly/d/schema-incompatibilities#mismatching-cuid-length

ALTER TABLE "default$default"."AccessToken" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."AccessToken" ALTER COLUMN "application" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."AccessToken" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Application" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Company" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Company" ALTER COLUMN "traderReceipt" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Company" ALTER COLUMN "transporterReceipt" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."CompanyAssociation" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."CompanyAssociation" ALTER COLUMN "company" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."CompanyAssociation" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Declaration" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."EcoOrganisme" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Form" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Form" ALTER COLUMN "temporaryStorageDetail" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Grant" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Grant" ALTER COLUMN "application" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Grant" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Installation" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."MembershipRequest" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."MembershipRequest" ALTER COLUMN "company" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."MembershipRequest" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."Rubrique" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."StatusLog" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."StatusLog" ALTER COLUMN "form" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."StatusLog" ALTER COLUMN "user" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."TemporaryStorageDetail" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."TraderReceipt" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."TransporterReceipt" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."TransportSegment" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."TransportSegment" ALTER COLUMN "form" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."User" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."UserAccountHash" ALTER COLUMN "id" SET DATA TYPE character varying(30);
ALTER TABLE "default$default"."UserActivationHash" ALTER COLUMN "id" SET DATA TYPE character varying(30);
