name: Build, test and deploy app

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
      - staging-*

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run typecheck
        run: npm run types
      - name: Run tests
        run: npm test

  back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run typecheck
        run: |
          npm run generate
          npm run types
      - name: Check migrations
        run: npm run check:migrations
      - name: Run tests
        run: npm test -- --forceExit
        env:
          JWT_SECRET: "xxx"
          EMAIL_BACKEND: "console"
          SIB_BASE_URL: "http://mailservice"
          MAIN_TEMPLATE_ID: "9"
          ONBOARDING_TEMPLATE_ID: "8"
          PRODUCER_SECOND_ONBOARDING_TEMPLATE_ID: "7"
          PROFESSIONAL_SECOND_ONBOARDING_TEMPLATE_ID: "9"
          SECURITY_CODE_RENEWAL_TEMPLATE_ID: "6"

  doc:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          yarn install --frozen-lockfile
          npm run build

  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back/integration-tests
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: |
          chmod +x ./run.sh
          ./run.sh

  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    needs: [front, back, integration-tests]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.CI_SSH_KEY }}
          known_hosts: ${{ secrets.CI_KNOWN_HOST }}
      - name: Deploy backend
        run: |
          chmod +x ./deploy-back.sh
          ./deploy-back.sh
        env:
          GIT_STAGING_1_BACK: ${{ secrets.GIT_STAGING_1_BACK }}
          GIT_PROD_BACK: "TODO"
          GIT_SANDBOX_BACK: "TODO"
          GIT_DEV_BACK: "TODO"

  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    needs: [front, back, integration-tests]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set bucket name
        run: |
          cd ../scripts
          chmod +x ./set-bucket.sh
          ./set-bucket.sh
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: "https://s3.fr-par.scw.cloud"
          AWS_REGION: "fr-par"
          SOURCE_DIR: "front/build"
