name: End-to-end tests

on: pull_request

jobs:
  back:
    runs-on: ubuntu-latest
    name: End-to-end tests (chunk ${{ matrix.shard }}/${{ strategy.job-total }})
    strategy:
      fail-fast: false
      matrix:
        shard: [1]
    defaults:
      run:
        working-directory: back/integration-tests
    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        env:
          TD_COMPANY_ELASTICSEARCH_URL: ${{ secrets.TD_COMPANY_ELASTICSEARCH_URL }}
          TD_COMPANY_ELASTICSEARCH_CACERT: ${{ secrets.TD_COMPANY_ELASTICSEARCH_CACERT }}

        run: |
          chmod +x ./run.sh
          ./run.sh -u
      - name: Stop containers
        env:
          TD_COMPANY_ELASTICSEARCH_URL: ${{ secrets.TD_COMPANY_ELASTICSEARCH_URL }}
          TD_COMPANY_ELASTICSEARCH_CACERT: ${{ secrets.TD_COMPANY_ELASTICSEARCH_CACERT }}

        run: |
          chmod +x ./run.sh
          ./run.sh -d