name: TypeScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - run: echo "::add-matcher::./.github/tsc.json"
      - run: npm --prefix ./back install
      - run: npx typescript --project ./back --strict
