-- AlterEnum
ALTER TYPE "TransportMode" ADD VALUE 'UNKNOWN';

-- AlterTable
ALTER TABLE "RegistryIncomingWaste" ADD COLUMN     "customInfo" TEXT,
ADD COLUMN     "nextDestinationIsAbroad" BOOLEAN,
ADD COLUMN     "nextOperationCode" TEXT;

-- CreateTable
CREATE TABLE "RegistryIncomingTexs" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "importId" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isCancelled" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT NOT NULL,
    "publicId" TEXT NOT NULL,
    "reportForSiret" TEXT NOT NULL,
    "reportForName" TEXT NOT NULL,
    "reportForAddress" TEXT NOT NULL,
    "reportForCity" TEXT NOT NULL,
    "reportForPostalCode" TEXT NOT NULL,
    "reportAsSiret" TEXT,
    "customInfo" TEXT,
    "wasteCode" TEXT NOT NULL,
    "wastePop" BOOLEAN NOT NULL,
    "wasteIsDangerous" BOOLEAN,
    "receptionDate" TIMESTAMP(3) NOT NULL,
    "wasteDescription" TEXT NOT NULL,
    "wasteCodeBale" TEXT,
    "dap" TEXT,
    "weightValue" DOUBLE PRECISION NOT NULL,
    "weightIsEstimate" BOOLEAN NOT NULL,
    "volume" DOUBLE PRECISION,
    "parcelInseeCodes" TEXT[],
    "parcelNumbers" TEXT[],
    "parcelCoordinates" TEXT[],
    "sisIdentifiers" TEXT[],
    "producerType" TEXT NOT NULL,
    "producerOrgId" TEXT,
    "producerName" TEXT,
    "producerAddress" TEXT,
    "producerPostalCode" TEXT,
    "producerCity" TEXT,
    "producerCountryCode" TEXT,
    "municipalitiesInseeCodes" TEXT[],
    "municipalitiesNames" TEXT[],
    "senderType" TEXT NOT NULL,
    "senderOrgId" TEXT,
    "senderName" TEXT,
    "senderTakeOverAddress" TEXT,
    "senderTakeOverPostalCode" TEXT,
    "senderTakeOverCity" TEXT,
    "senderTakeOverCountryCode" TEXT,
    "senderAddress" TEXT,
    "senderPostalCode" TEXT,
    "senderCity" TEXT,
    "senderCountryCode" TEXT,
    "brokerSiret" TEXT,
    "brokerName" TEXT,
    "brokerReceiptNumber" TEXT,
    "traderSiret" TEXT,
    "traderName" TEXT,
    "traderReceiptNumber" TEXT,
    "operationCode" TEXT NOT NULL,
    "nextDestinationIsAbroad" BOOLEAN,
    "declarationNumber" TEXT,
    "notificationNumber" TEXT,
    "movementNumber" TEXT,
    "nextOperationCode" TEXT,
    "isUpcycled" BOOLEAN,
    "destinationParcelInseeCodes" TEXT[],
    "destinationParcelNumbers" TEXT[],
    "destinationParcelCoordinates" TEXT[],
    "transporter1TransportMode" "TransportMode" NOT NULL,
    "transporter1Type" TEXT NOT NULL,
    "transporter1OrgId" TEXT,
    "transporter1ReceiptNumber" TEXT,
    "transporter1Name" TEXT,
    "transporter1Address" TEXT,
    "transporter1PostalCode" TEXT,
    "transporter1City" TEXT,
    "transporter1CountryCode" TEXT,
    "transporter2TransportMode" "TransportMode",
    "transporter2Type" TEXT,
    "transporter2OrgId" TEXT,
    "transporter2ReceiptNumber" TEXT,
    "transporter2Name" TEXT,
    "transporter2Address" TEXT,
    "transporter2PostalCode" TEXT,
    "transporter2City" TEXT,
    "transporter2CountryCode" TEXT,
    "transporter3TransportMode" "TransportMode",
    "transporter3Type" TEXT,
    "transporter3OrgId" TEXT,
    "transporter3ReceiptNumber" TEXT,
    "transporter3Name" TEXT,
    "transporter3Address" TEXT,
    "transporter3PostalCode" TEXT,
    "transporter3City" TEXT,
    "transporter3CountryCode" TEXT,
    "transporter4TransportMode" "TransportMode",
    "transporter4Type" TEXT,
    "transporter4OrgId" TEXT,
    "transporter4ReceiptNumber" TEXT,
    "transporter4Name" TEXT,
    "transporter4Address" TEXT,
    "transporter4PostalCode" TEXT,
    "transporter4City" TEXT,
    "transporter4CountryCode" TEXT,
    "transporter5TransportMode" "TransportMode",
    "transporter5Type" TEXT,
    "transporter5OrgId" TEXT,
    "transporter5ReceiptNumber" TEXT,
    "transporter5Name" TEXT,
    "transporter5Address" TEXT,
    "transporter5PostalCode" TEXT,
    "transporter5City" TEXT,
    "transporter5CountryCode" TEXT,

    CONSTRAINT "RegistryIncomingTexs_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "RegistryIncomingTexs" ADD CONSTRAINT "RegistryIncomingTexs_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
